version: "3.8"

services:

  namenode:
    image: ramilu90/hadoop-namenode
    container_name: namenode
    platform: linux/amd64
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - /home/iitgcpuser/Big-Data-Programming-Task-02:/opt/resources
      - ./hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=task03
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net

  datanode:
    image: ramilu90/hadoop-datanode
    container_name: datanode
    platform: linux/amd64
    restart: always
    volumes:
      - ./hdfs/datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks:
      - hadoop-net

  spark-master:
    image: ramilu90/spark-master
    container_name: spark-master
    platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - /home/iitgcpuser/Big-Data-Programming-Task-02:/opt/resources
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - INIT_DAEMON_STEP=setup_spark
    depends_on:
      - namenode
      - datanode
    networks:
      - hadoop-net

  spark-worker-1:
    image: ramilu90/spark-worker
    container_name: spark-worker-1
    platform: linux/amd64
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - spark-master
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge
