version: "3"

services:
  zeppelin:
    image: apache/zeppelin:0.11.1
    container_name: zeppelin
    restart: always
    user: "0:0"  # Run as root to avoid permission issues
    ports:
      - "8089:8080"
    volumes:
      - /home/iitgcpuser/Big-Data-Programming-Task-02/resources:/opt/resources
      - /home/iitgcpuser/Big-Data-Programming-Task-02/scripts:/opt/scripts
      - /home/iitgcpuser/Big-Data-Programming-Task-02/zeppelin_notebooks:/opt/zeppelin/notebook
      - /home/iitgcpuser/Big-Data-Programming-Task-02/conf:/opt/zeppelin/conf
      - /home/iitgcpuser/Big-Data-Programming-Task-02/spark:/opt/spark  # This provides spark-submit
    environment:
      SPARK_HOME: "/opt/spark"
      ZEPPELIN_ADDR: "0.0.0.0"
