version: "3"

services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    restart: always
    user: "1001:1001"
    ports:
      - "8089:8080"
    volumes:
      - /home/iitgcpuser/Big-Data-Programming-Task-02/resources:/opt/resources
      - /home/iitgcpuser/Big-Data-Programming-Task-02/scripts:/opt/scripts
      - /home/iitgcpuser/Big-Data-Programming-Task-02/zeppelin_notebooks:/opt/zeppelin/notebook
    environment:
      ZEPPELIN_ADDR: "0.0.0.0"
      SPARK_HOME: "/opt/spark"
